### ISSUE TITLE
Mongo - Injest script : mongo client seams to be closed at the wrong time

### ISSUE THREAD

**Issue by nelt** [nelt/ufc-m1-ead-info-nosql-workbench#9]
Sistematically at the end of the import, exception thrown : 
Read 529998 rows data-set in 1187.855s.
(node:14) UnhandledPromiseRejectionWarning: MongoError: server is closed
    at executeWriteOperation (/usr/src/app/node_modules/mongodb/lib/core/sdam/server.js:474:14)
    at Server.update (/usr/src/app/node_modules/mongodb/lib/core/sdam/server.js:423:5)
    at Object.topology.selectServer [as callback] (/usr/src/app/node_modules/mongodb/lib/core/sdam/topology.js:969:15)
    at processWaitQueue (/usr/src/app/node_modules/mongodb/lib/core/sdam/topology.js:1090:21)
    at NativeTopology.selectServer (/usr/src/app/node_modules/mongodb/lib/core/sdam/topology.js:459:5)
    at executeWriteOperation (/usr/src/app/node_modules/mongodb/lib/core/sdam/topology.js:937:12)
    at NativeTopology.update (/usr/src/app/node_modules/mongodb/lib/core/sdam/topology.js:627:5)
    at NativeTopology.update (/usr/src/app/node_modules/mongodb/lib/topologies/native_topology.js:59:11)
    at updateDocuments (/usr/src/app/node_modules/mongodb/lib/operations/common_functions.js:370:19)
    at UpdateOneOperation.execute (/usr/src/app/node_modules/mongodb/lib/operations/update_one.js:24:5)
(node:14) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:14) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by DavidPrevot** [comment]
Maybe related: calling the script with an argument does not close the connection.

```
$ time docker-compose exec workbench node app.js --batch /workspace/fifa-2018-tweets/mongo/injest-mongo.js 10
starting in batch mode with arguments : /workspace/fifa-2018-tweets/mongo/injest-mongo.js :: 10
running /workspace/fifa-2018-tweets/mongo/injest-mongo.js
will read 10 records from FIFA.csv
max read reached
```

(Use Ctrl C when bored.)
